IMAGE:
    SIZE: [256, 256]

WATERMARK:
    NUM_BITS: 256
    ECC_MODE: ecc
    ECC_T: 16
    ECC_M: 8

ENCODER:
    NUM_DOWN_LEVELS: 4
    NUM_INITIAL_CHANNELS: 32
    HIDDEN_DIM: 16
    NUM_FRAMES: 1
    ADAPTIVE_WATERMARK:
        ENABLED: true
        D_MODEL: 128
        NUM_TRANSFORMER_LAYERS: 2
        NUM_ATTENTION_HEADS: 4
        USE_SPATIAL_ATTENTION: true

DECODER:
    NAME: IMAGENET1K_V1

DISCRIMINATOR:
    NAME: ResNet18_Weights.IMAGENET1K_V1
    NUM_CLASSES: 1
